apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: celery-service
  name: celery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: celery-service
    spec:
      containers:
      - image: vikasit/celery_service:1.0
        imagePullPolicy: IfNotPresent
        name: celery-app
      hostname: celery
      initContainers:
      - command:
        - /bin/sh
        - -c
        - until nslookup redis; do echo waiting for redis; sleep 2; done;
        image: busybox:latest
        imagePullPolicy: Always
        name: init-redis
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

